# site settings
title: Vega
subtitle: Galactic
description: A Hex tile strategy game set in space
baseurl: "/spaceeducation" # the subpath of your site, e.g. /blog
url: "https://fedg-code.github.io/" # the base hostname & protocol for your site

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

# social settings
500px_url:
facebook_url:
github_url: https://fedg-code.github.io/spaceeducation/

# build settings
markdown: kramdown

sass:
  style: compressed
